import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        "headline-md": ["'EB Garamond'", "serif"],
        "headline-lg": ["'EB Garamond'", "serif"],
        "headline-lg-mobile": ["'EB Garamond'", "serif"],
        "body-lg": ["'DM Sans'", "sans-serif"],
        "body-md": ["'DM Sans'", "sans-serif"],
        "label-md": ["'DM Sans'", "sans-serif"],
        "display-lg-mobile": ["'EB Garamond'", "serif"],
        "display-lg": ["'EB Garamond'", "serif"],
        display: ["'EB Garamond'", "serif"],
        body: ["'DM Sans'", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "500" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.3", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", fontWeight: "400" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "400" }],
      },
      spacing: {
        "margin-desktop": "64px",
        gutter: "24px",
        "container-max": "1280px",
        unit: "8px",
        "margin-mobile": "20px",
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "#fcf9f8",
        foreground: "#1b1c1c",
        primary: {
          DEFAULT: "#9a4025",
          foreground: "#ffffff",
        },
        secondary: {
          DEFAULT: "#625e54",
          foreground: "#ffffff",
        },
        destructive: {
          DEFAULT: "#ba1a1a",
          foreground: "#ffffff",
        },
        muted: {
          DEFAULT: "#e4e2e1",
          foreground: "#56423d",
        },
        accent: {
          DEFAULT: "#e6dfd2",
          foreground: "#676258",
        },
        popover: {
          DEFAULT: "#ffffff",
          foreground: "#1b1c1c",
        },
        card: {
          DEFAULT: "#f6f3f2",
          foreground: "#1b1c1c",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        "on-primary-fixed": "#3b0900",
        "surface-variant": "#e4e2e1",
        "surface-container-highest": "#e4e2e1",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#f3f0f0",
        tertiary: "#5d5c58",
        "tertiary-fixed-dim": "#c8c6c2",
        outline: "#89726c",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#7e2b12",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#474743",
        "surface-bright": "#fcf9f8",
        "primary-fixed-dim": "#ffb5a0",
        "primary-fixed": "#ffdbd1",
        "on-tertiary": "#ffffff",
        "on-background": "#1b1c1c",
        "primary-container": "#ba573b",
        "tertiary-fixed": "#1c1c19",
        "surface-container": "#f0eded",
        "on-primary-container": "#fffbff",
        "secondary-container": "#e6dfd2",
        "on-surface-variant": "#56423d",
        "on-error-container": "#93000a",
        error: "#ba1a1a",
        "on-secondary-container": "#676258",
        "outline-variant": "#dcc0b9",
        "inverse-surface": "#303030",
        "surface-container-high": "#eae7e7",
        "surface-tint": "#9d4227",
        "on-surface": "#1b1c1c",
        "secondary-fixed-dim": "#ccc6b9",
        "inverse-primary": "#ffb5a0",
        surface: "#fcf9f8",
        "on-secondary-fixed": "#1e1b13",
        "on-secondary-fixed-variant": "#4a463d",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "on-tertiary-container": "#fcffe3",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
        md: "0.25rem",
        sm: "0.125rem",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
